name: DevSecOps Pipeline with Trivy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy_scan:
    name: Run Trivy Security Scan on Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t vulnerable-python-app:latest .

      # Step 4: Run Trivy scan using Trivy Action
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'vulnerable-python-app:latest'
          format: 'json'  # You can change to 'json' or 'html' for different output formats
          severity: 'HIGH,CRITICAL'  # Scan only for High and Critical vulnerabilities
          #exit-code: 1  # Fail the build if vulnerabilities are found
          output: 'scan-report.txt'

      # Step 5: Upload the Trivy report (optional)
      - name: Upload Trivy scan report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-scan-report
          path: trivy-report.json

      - name: Publish Trivy Output to Summary
        if: success()
        run: |
          if [[ -s scan-report.txt ]]; then
             {
               echo "#### Security Output"
               echo "<details><summary>Click to expand</summary>"
               echo '```'
               cat scan-report.txt
               echo '```'
               echo "</details>"
             } >> $GITHUB_STEP_SUMMARY
          else
            echo "No vulnerabilities found"
          fi
